version: '3.8'
services:
  postgres-api:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_API}
    ports:
      - "5432:5432"
    volumes:
      - postgres-api-data:/var/lib/postgresql/data
    networks:
      - monorepo-net
volumes:
  postgres-api-data:
